//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class assurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assurance()
        {
            this.ligne_echeancier_assurance = new HashSet<ligne_echeancier_assurance>();
        }
    
        public int id_assurance { get; set; }
        public string compagnie { get; set; }
        public string frequence_paiement { get; set; }
        public string garantie { get; set; }
        public Nullable<int> id_pret { get; set; }
    
        public virtual pret pret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_echeancier_assurance> ligne_echeancier_assurance { get; set; }
    }
}
