//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class frais_pret
    {
        public int id_frais_pret { get; set; }
        public string nom { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<System.DateTime> date_paiement { get; set; }
        public string statut { get; set; }
        public string informations_complementaires { get; set; }
        public Nullable<int> id_pret { get; set; }
    
        public virtual pret pret { get; set; }
    }
}
