//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_echeancier_assurance
    {
        public int id_ligne_echeancier_assurance { get; set; }
        public string nom { get; set; }
        public Nullable<System.DateTime> date_prelevement { get; set; }
        public string motif { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public string statut { get; set; }
        public Nullable<int> id_assurance { get; set; }
    
        public virtual assurance assurance { get; set; }
    }
}
