//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class logement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logement()
        {
            this.charge = new HashSet<charge>();
            this.deblocage_fond = new HashSet<deblocage_fond>();
            this.frais = new HashSet<frais>();
            this.piece = new HashSet<piece>();
            this.pret = new HashSet<pret>();
            this.remboursement = new HashSet<remboursement>();
        }
    
        public int id_logement { get; set; }
        public byte[] photo { get; set; }
        public string nom { get; set; }
        public string adresse { get; set; }
        public Nullable<int> code_postal { get; set; }
        public string ville { get; set; }
        public string taille { get; set; }
        public string type_logement { get; set; }
        public string utilisation { get; set; }
        public Nullable<int> annee_construction { get; set; }
        public string informations_complementaires { get; set; }
        public string regles_fiscales { get; set; }
        public Nullable<int> prix_achat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<charge> charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deblocage_fond> deblocage_fond { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frais> frais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<piece> piece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pret> pret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remboursement> remboursement { get; set; }
    }
}
