//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece
    {
        public int id_piece { get; set; }
        public Nullable<double> taille { get; set; }
        public string mesure { get; set; }
        public Nullable<int> id_logement { get; set; }
    
        public virtual logement logement { get; set; }
    }
}
