//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestImmo.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class remboursement
    {
        public int id_remboursement { get; set; }
        public string nom { get; set; }
        public Nullable<double> montant_paye { get; set; }
        public Nullable<double> montant_total { get; set; }
        public Nullable<int> id_logement { get; set; }
    
        public virtual logement logement { get; set; }
    }
}
